@extends('frontend.layout')
@section('extern-css')
<link rel="stylesheet" type="text/css" href="{{ url('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">

 
@endsection
@section('content')

{{-- <main>
        <!-- breadcrumb area start -->
        
        <!-- breadcrumb area end -->

        <!-- blog main wrapper start -->
        <div class="blog-main-wrapper section-padding">
            <div class="container">
                <div class="row">
                   
                    <div class="col-lg-12 order-1">
                        <div class="row">
                            <div class="col-12">
                                <!-- blog single item start -->
                                <div class="blog-post-item">
                                    
                                    <div class="blog-content blog-details">
                                        <h5 class="blog-title">
                                            General
                                        </h5>
                                       
                                        <p>Reliance Brands Limited, having its registered address at 5th Floor, Court House, Lokmanya Tilak Marg, Dhobi Talao, Maharashtra, Mumbai 400002, India (“Reliance”, “we”, “us” or “our”) is managing and operating the mobile application/website stevemadden.in (collectively referred to as the “Steve Madden Platform”) through which it inter alia facilitates the sale of lifestyle and fashion merchandise products (“Products”) to the users of the Steve Madden Platform (“User” or “Users” or “you” or “your”).  
This privacy policy (“Privacy Policy”), together with the governs your use of the Steve Madden Platform and describes our policies and procedures on the collection, use, disclosure, processing, transfer, and storage of the information provided to us by you. By using, browsing, accessing, or purchasing from the Steve Madden Platform you agree to be bound by the terms of this Privacy Policy and consent to the collection, storage, possession, dealing, handling, sharing, disclosure or transfer of your information in accordance with the terms of the Privacy Policy. We shall not use the User’s information in any manner except as provided under this Privacy Policy. Capitalised terms used herein if not defined shall have the same meaning as ascribed to them under the Terms.
This document is an electronic record and is governed by the provisions under the Information Technology Act, 2000 and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
This Privacy Policy sets out the type of information collected from the Users, including the nature of the Sensitive Personal Data or Information (defined hereinafter), the purpose, means and modes of usage of such information and how and to whom we shall disclose or transfer such information. You may at any time withdraw your consent for collection and use of your information including Personal Information (defined hereinafter) or Sensitive Personal Data or Information. However, please note that if you withdraw your consent, we may no longer be able to provide you with the corresponding service for which you have withdrawn your consent. It is hereby clarified that your decision to withdraw your consent will not affect the processing of Personal Information based on your previous consent prior to the withdrawal.
Please take a moment to familiarize yourself with our Privacy Policy. If you do not agree with any provisions of the Terms or this Privacy Policy, we advise you to not use or access the Steve Madden Platform.
                                        </p>
                                    </div>

                                    <div class="blog-content blog-details">
                                        <h5 class="blog-title">
                                            Type of Information Collected
                                        </h5>
                                       
                                        <p>You may be asked to provide your information anytime you visit, access, use or browse the Steve Madden Platform. We may share information and use it consistent with the provisions of this Privacy Policy. We may also combine it with other information to provide and improve our Products, services, content and advertising.
You agree to provide information, which shall be true, correct, up to date and accurate. You may access, amend, alter or require deletion of your information partially or fully by contacting us at support@stevemadden.in.
Steve Madden Platform is not directed towards minors. We do not knowingly collect Personal Information from any User who is under 18 (Eighteen) years. If we are made aware that we have collected the Personal Information of a person below the age of 18 (Eighteen) years, we will take steps to delete the information within a reasonable time frame. If a parent or guardian becomes aware that his or her child has provided his/ her information on the Steve Madden Platform without their consent, he or she shall contact us for the deletion of such information. In the event, where in contravention to the Privacy Policy and Terms, a person below the age of 18 (Eighteen) uses the services, we shall not be held liable or responsible for any damage or injury suffered by such person.
2.4       We may collect a variety of information from you, including your name, password, mailing address, phone number, email address and contact preferences, including any other usage and interaction details with us or our affiliates. We may collect such information which when combined with other pieces of information available with us could reasonably allow you to be identified (“Personal Information”). Personal Information shall include but is not limited to your full name, personal contact numbers, residential address, email address, gender or date of birth.

2.5        We may also collect, receive, process or store certain sensitive personal data or information consisting of, but not limited to:

Password;
Financial information such as bank account or credit card or debit card or other payment instrument details;
Physical, physiological and mental health condition;
Any detail relating to the above Personal Information categories as provided to us for providing service; and
Any of the information received under above Personal Information categories by us for processing, stored or processed under lawful contract or otherwise.
(Collectively, referred to as “Sensitive Personal Data or Information”).
                                        </p>
                                    </div><div class="blog-content blog-details">
                                        <h5 class="blog-title">
                                            Use of Information Collected
                                        </h5>
                                       
                                        <p>3.1       We may collect, use or process your information including Personal Information and Sensitive Personal Data or Information for the following purposes:

3.1.1     For creating and giving you access to your registered account on the Steve Madden Platform.

3.1.2     To develop, deliver, process and improve our Products, services, content in order to personalize and improve your experience.

3.1.3     To inform you about our Products, services, offers, updates, upcoming events, including providing you information in relation to order confirmations, invoices, technical notices, security alerts.

3.1.4     For internal analytical and research purposes such as auditing, data analysis and research to improve Our Products, services and customer communications.

3.1.5     To meet any legal or regulatory requirement or comply with a request from any governmental or judicial authority.

3.1.6     To resolve any request, dispute, grievance or complaint raised by you in relation to your use of the Steve Madden Platform.

3.1.7     To detect or monitor any fraudulent or illegal activity on the Steve Madden Platform.
                                        </p>
                                    </div>
                                    <div class="blog-content blog-details">
                                        <h5 class="blog-title">
                                            Disclosure of Information Collected
                                        </h5>
                                       
                                        <p>4.1       We may from time to time be required to disclose the information collected from you to our trusted third party service providers who assist us in order to facilitate the provision of services and purchase of Products on the Steve Madden Platform. For instance, we may share your information with third party payment gateway provider to process transactions on the Steve Madden Platform. By using the Steve Madden Platform, you consent to any such disclosure of your information with third party service providers. We ensure that such third party service providers are bound by reasonable confidentiality obligations and/ or use, maintain and follow generally accepted industry and security standards with respect to such information.

4.2       We may also disclose your information when such disclosure is requisitioned under any law or judicial decree or when we, in our sole discretion, deem it necessary in order to protect our rights or the rights of other Users, to prevent harm to persons or property, to fight fraud and credit risk.

4.3       We may also disclose or transfer your information to any third party as a part of reorganization or a sale of the assets, division or transfer of a part or whole of us. We shall ensure that third party to which we transfer or sell our assets will have appropriate confidentiality and security measures, at least as protective as those described in this Privacy Policy, to handle your Personal Information. You will have the opportunity to opt out of any such transfer if the new entity's planned processing of your information differs materially from that set forth in this Privacy Policy.

4.4       A third party payment gateway provider may be required to collect certain financial information from you including, but not restricted to, your credit/debit card number or your bank account details (collectively referred to as “Financial Information”). All Financial Information collected from the you by such third party payment gateway providers will be used only for billing and payment processes. The Financial Information collected from you is transacted through secure digital platforms of approved payment gateways which are under encryption, thereby complying with reasonably expected technology standards. The verification of the Financial Information shall be accomplished only by you through a process of authentication in which we shall have no role to play and hence, we shall bear no liability in relation to the same. We shall neither be liable nor responsible for any actions or inactions of third party payment gateway providers or any breach of conditions, representations and warranties given by them. We shall also not be obligated to mediate or resolve any dispute or disagreement between you and such third party payment service providers.

4.5       While we take best efforts to ensure that your information including Personal Information, Financial Information and Sensitive Personal Information or Data is duly protected by undertaking security measures prescribed under applicable laws, you are strongly advised to exercise reasonable discretion while providing Personal Information or Financial Information while using the services given that the Internet is susceptible to security breaches.

4.6       Your information may also be transferred, stored or processed in any country other than the one where you access the Steve Madden Platform. For purposes of sharing or disclosing data in accordance with the Privacy Policy, we reserve the right to transfer your information outside of your country. By using the Steve Madden Platform, you consent to such transfer of your information outside of your country and also within our affiliates, subsidiaries and partners whose personnel and subcontractors, provided they have agreed to ensure the same level of data protection as prescribed under this Privacy Policy and the data protection laws of India. The information may be transferred in the event it is necessary for the performance of the services, operation of the Steve Madden Platform and provision of Products as agreed upon between us and the third party.
                                        </p>
                                    </div><div class="blog-content blog-details">
                                        <h5 class="blog-title">
                                            Security
                                        </h5>
                                       
                                        <p>5.1       The security of your Personal Information is important to us. We have implemented security policies, rules and technical measures, as required under applicable law including firewalls, transport layer security and other physical and electronic security measures to protect the Personal Information that it has under its control from unauthorized access, improper use or disclosure, unauthorized modification and unlawful destruction or accidental loss. When you submit your information on the Steve Madden Platform, your information is protected through our security systems. Please note that we use international and industry-recognized standards such as per applicable laws, rules and regulations.

5.2       Your information is contained within secured networks and is only accessible by a limited number of authorized persons who have access rights to such systems or otherwise require such information for the purposes provided in this Privacy Policy. These authorized persons are also under an obligation to keep such information confidential.

5.3       Although we make best possible efforts to transmit and store all the information provided by you in a secure operating environment that is not open to public, you understand and acknowledge that there is no such thing as complete security and we do not guarantee that there will be no unintended disclosures of any information and potential security breaches. You agree not to hold us responsible for any breach of security or for any action of any third parties that receive your Personal Information or events that are beyond our reasonable control including, acts of government, computer hacking, unauthorized access to computer data and storage device, computer crashes, breach of security and encryption, etc.
                                        </p>
                                    </div>
                                </div>
                              
                           
                            <!-- start blog comment box -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- blog main wrapper end -->
    </main> --}}

    <div class="mb-3 mb-xl-5 pt-1 pb-4"></div>
    <div class="mb-3 mb-xl-5 pt-1 pb-4"></div>
    <main>
        {{-- <div class="mb-4 pb-4"></div> --}}
        <section class="about-us container" style=" max-width: 100%; ">
          {{-- <div class="mw-930">
            <h2 class="page-title">ABOUT Walkcy</h2>
          </div> --}}
          <div class="about-us__content pb-5 mb-5">
            <div class="blog-main-wrapper section-padding">
                <div class="container">
                    <div class="row">
                       
                        <div class="col-lg-12 order-1">
                            <div class="row">
                                <div class="col-12">
                                    <!-- blog single item start -->
                                    <div class="blog-post-item">
                                        
                                        <h1>Return and Refund Policy</h1>
                                        <p>Last updated: June 14, 2024</p>
                                        <p>Thank you for shopping at Walkcy.</p>
                                        <p>If, for any reason, You are not completely satisfied with a purchase We invite You to review our policy on refunds and returns.</a>.</p>
                                        <p>The following terms are applicable for any products that You purchased with Us.</p>
                                        <h2>Interpretation and Definitions</h2>
                                        <h3>Interpretation</h3>
                                        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                                        <h3>Definitions</h3>
                                        <p>For the purposes of this Return and Refund Policy:</p>
                                        <ul>
                                        <li>
                                        <p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Walkcy, Hanumangadi Mandir, Walkcy, Ram path Road, beside sagar Life Style, Rikabganj, Faizabad, Uttar Pradesh 224001.</p>
                                        </li>
                                        <li>
                                        <p><strong>Goods</strong> refer to the items offered for sale on the Service.</p>
                                        </li>
                                        <li>
                                        <p><strong>Orders</strong> mean a request by You to purchase Goods from Us.</p>
                                        </li>
                                        <li>
                                        <p><strong>Service</strong> refers to the Website.</p>
                                        </li>
                                        <li>
                                        <p><strong>Website</strong> refers to Walkcy, accessible from <a href="https://walkcy.com/" rel="external nofollow noopener" target="_blank">https://walkcy.com/</a></p>
                                        </li>
                                        <li>
                                        <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                                        </li>
                                        </ul>
                                        <h2>Your Order Cancellation Rights</h2>
                                        <p>You are entitled to cancel Your Order within 14 days without giving any reason for doing so.</p>
                                        <p>The deadline for cancelling an Order is 14 days from the date on which You received the Goods or on which a third party you have appointed, who is not the carrier, takes possession of the product delivered.</p>
                                        <p>In order to exercise Your right of cancellation, You must inform Us of your decision by means of a clear statement. You can inform us of your decision by:</p>
                                        <ul>
                                        <li>
                                        <p>By email: help@walkcy.com</p>
                                        </li>
                                        <li>
                                        <p>By phone number: 093353 36433</p>
                                        </li>
                                        </ul>
                                        <p>We will reimburse You no later than 14 days from the day on which We receive the returned Goods. We will use the same means of payment as You used for the Order, and You will not incur any fees for such reimbursement.</p>
                                        <h2>Conditions for Returns</h2>
                                        <p>In order for the Goods to be eligible for a return, please make sure that:</p>
                                        <ul>
                                        <li>The Goods were purchased in the last 14 days</li>
                                        <li>The Goods are in the original packaging</li>
                                        </ul>
                                        <p>The following Goods cannot be returned:</p>
                                        <ul>
                                        <li>The supply of Goods made to Your specifications or clearly personalized.</li>
                                        <li>The supply of Goods which according to their nature are not suitable to be returned, deteriorate rapidly or where the date of expiry is over.</li>
                                        <li>The supply of Goods which are not suitable for return due to health protection or hygiene reasons and were unsealed after delivery.</li>
                                        <li>The supply of Goods which are, after delivery, according to their nature, inseparably mixed with other items.</li>
                                        </ul>
                                        <p>We reserve the right to refuse returns of any merchandise that does not meet the above return conditions in our sole discretion.</p>
                                        <p>Only regular priced Goods may be refunded. Unfortunately, Goods on sale cannot be refunded. This exclusion may not apply to You if it is not permitted by applicable law.</p>
                                        <h2>Returning Goods</h2>
                                        <p>You are responsible for the cost and risk of returning the Goods to Us. You should send the Goods at the following address:</p>
                                        <p>Hanumangadi Mandir, Walkcy, Ram path Road, beside sagar Life Style, Rikabganj, Faizabad, Uttar Pradesh 224001</p>
                                        <p>We cannot be held responsible for Goods damaged or lost in return shipment. Therefore, We recommend an insured and trackable mail service. We are unable to issue a refund without actual receipt of the Goods or proof of received return delivery.</p>
                                        <h2>Gifts</h2>
                                        <p>If the Goods were marked as a gift when purchased and then shipped directly to you, You'll receive a gift credit for the value of your return. Once the returned product is received, a gift certificate will be mailed to You.</p>
                                        <p>If the Goods weren't marked as a gift when purchased, or the gift giver had the Order shipped to themselves to give it to You later, We will send the refund to the gift giver.</p>
                                        <h3>Contact Us</h3>
                                        <p>If you have any questions about our Returns and Refunds Policy, please contact us:</p>
                                        <ul>
                                        <li>
                                        <p>By email: help@walkcy.com</p>
                                        </li>
                                        <li>
                                        <p>By phone number: 093353 36433</p>
                                        </li>
                                        </ul>
                                        


    
                                        
                                    </div>
                                  
                               
                                <!-- start blog comment box -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </section>
        
      
   
      </main>
    


@endsection
@section('extern-js')

<script src="{{url('plugins\datatables\jquery.dataTables.min.js')}}"></script>
<script src="{{url('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{url('plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{url('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{url('frontend_assets/custom_js/cart.js')}}"></script>
<script type="text/javascript"> $(document).ready(function(){
$(".small_img").hover (function(){
$(".big_img").attr('src', $(this).attr('src'));
});
});
</script>
<script type="text/javascript">
	$(document).ready(function(){
		$('#imgs').imagezoomsl({
			zoomrange:[3,3]
		});
	});
	function bigImg(obj){
		console.log(obj);
	}
</script>
@endsection