@extends('frontend.layout')
@section('extern-css')
<link rel="stylesheet" type="text/css" href="{{ url('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ url('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">

 
@endsection
@section('content')

{{-- <main>
        <!-- breadcrumb area start -->
        
        <!-- breadcrumb area end -->

        <!-- blog main wrapper start -->
        <div class="blog-main-wrapper section-padding">
            <div class="container">
                <div class="row">
                   
                    <div class="col-lg-12 order-1">
                        <div class="row">
                            <div class="col-12">
                                <!-- blog single item start -->
                                <div class="blog-post-item">
                                    
                                    <div class="blog-content blog-details">
                                        <h5 class="blog-title">
                                            General
                                        </h5>
                                       
                                        <p>Reliance Brands Limited, having its registered address at 5th Floor, Court House, Lokmanya Tilak Marg, Dhobi Talao, Maharashtra, Mumbai 400002, India (“Reliance”, “we”, “us” or “our”) is managing and operating the mobile application/website stevemadden.in (collectively referred to as the “Steve Madden Platform”) through which it inter alia facilitates the sale of lifestyle and fashion merchandise products (“Products”) to the users of the Steve Madden Platform (“User” or “Users” or “you” or “your”).  
This privacy policy (“Privacy Policy”), together with the governs your use of the Steve Madden Platform and describes our policies and procedures on the collection, use, disclosure, processing, transfer, and storage of the information provided to us by you. By using, browsing, accessing, or purchasing from the Steve Madden Platform you agree to be bound by the terms of this Privacy Policy and consent to the collection, storage, possession, dealing, handling, sharing, disclosure or transfer of your information in accordance with the terms of the Privacy Policy. We shall not use the User’s information in any manner except as provided under this Privacy Policy. Capitalised terms used herein if not defined shall have the same meaning as ascribed to them under the Terms.
This document is an electronic record and is governed by the provisions under the Information Technology Act, 2000 and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
This Privacy Policy sets out the type of information collected from the Users, including the nature of the Sensitive Personal Data or Information (defined hereinafter), the purpose, means and modes of usage of such information and how and to whom we shall disclose or transfer such information. You may at any time withdraw your consent for collection and use of your information including Personal Information (defined hereinafter) or Sensitive Personal Data or Information. However, please note that if you withdraw your consent, we may no longer be able to provide you with the corresponding service for which you have withdrawn your consent. It is hereby clarified that your decision to withdraw your consent will not affect the processing of Personal Information based on your previous consent prior to the withdrawal.
Please take a moment to familiarize yourself with our Privacy Policy. If you do not agree with any provisions of the Terms or this Privacy Policy, we advise you to not use or access the Steve Madden Platform.
                                        </p>
                                    </div>

                                    <div class="blog-content blog-details">
                                        <h5 class="blog-title">
                                            Type of Information Collected
                                        </h5>
                                       
                                        <p>You may be asked to provide your information anytime you visit, access, use or browse the Steve Madden Platform. We may share information and use it consistent with the provisions of this Privacy Policy. We may also combine it with other information to provide and improve our Products, services, content and advertising.
You agree to provide information, which shall be true, correct, up to date and accurate. You may access, amend, alter or require deletion of your information partially or fully by contacting us at support@stevemadden.in.
Steve Madden Platform is not directed towards minors. We do not knowingly collect Personal Information from any User who is under 18 (Eighteen) years. If we are made aware that we have collected the Personal Information of a person below the age of 18 (Eighteen) years, we will take steps to delete the information within a reasonable time frame. If a parent or guardian becomes aware that his or her child has provided his/ her information on the Steve Madden Platform without their consent, he or she shall contact us for the deletion of such information. In the event, where in contravention to the Privacy Policy and Terms, a person below the age of 18 (Eighteen) uses the services, we shall not be held liable or responsible for any damage or injury suffered by such person.
2.4       We may collect a variety of information from you, including your name, password, mailing address, phone number, email address and contact preferences, including any other usage and interaction details with us or our affiliates. We may collect such information which when combined with other pieces of information available with us could reasonably allow you to be identified (“Personal Information”). Personal Information shall include but is not limited to your full name, personal contact numbers, residential address, email address, gender or date of birth.

2.5        We may also collect, receive, process or store certain sensitive personal data or information consisting of, but not limited to:

Password;
Financial information such as bank account or credit card or debit card or other payment instrument details;
Physical, physiological and mental health condition;
Any detail relating to the above Personal Information categories as provided to us for providing service; and
Any of the information received under above Personal Information categories by us for processing, stored or processed under lawful contract or otherwise.
(Collectively, referred to as “Sensitive Personal Data or Information”).
                                        </p>
                                    </div><div class="blog-content blog-details">
                                        <h5 class="blog-title">
                                            Use of Information Collected
                                        </h5>
                                       
                                        <p>3.1       We may collect, use or process your information including Personal Information and Sensitive Personal Data or Information for the following purposes:

3.1.1     For creating and giving you access to your registered account on the Steve Madden Platform.

3.1.2     To develop, deliver, process and improve our Products, services, content in order to personalize and improve your experience.

3.1.3     To inform you about our Products, services, offers, updates, upcoming events, including providing you information in relation to order confirmations, invoices, technical notices, security alerts.

3.1.4     For internal analytical and research purposes such as auditing, data analysis and research to improve Our Products, services and customer communications.

3.1.5     To meet any legal or regulatory requirement or comply with a request from any governmental or judicial authority.

3.1.6     To resolve any request, dispute, grievance or complaint raised by you in relation to your use of the Steve Madden Platform.

3.1.7     To detect or monitor any fraudulent or illegal activity on the Steve Madden Platform.
                                        </p>
                                    </div>
                                    <div class="blog-content blog-details">
                                        <h5 class="blog-title">
                                            Disclosure of Information Collected
                                        </h5>
                                       
                                        <p>4.1       We may from time to time be required to disclose the information collected from you to our trusted third party service providers who assist us in order to facilitate the provision of services and purchase of Products on the Steve Madden Platform. For instance, we may share your information with third party payment gateway provider to process transactions on the Steve Madden Platform. By using the Steve Madden Platform, you consent to any such disclosure of your information with third party service providers. We ensure that such third party service providers are bound by reasonable confidentiality obligations and/ or use, maintain and follow generally accepted industry and security standards with respect to such information.

4.2       We may also disclose your information when such disclosure is requisitioned under any law or judicial decree or when we, in our sole discretion, deem it necessary in order to protect our rights or the rights of other Users, to prevent harm to persons or property, to fight fraud and credit risk.

4.3       We may also disclose or transfer your information to any third party as a part of reorganization or a sale of the assets, division or transfer of a part or whole of us. We shall ensure that third party to which we transfer or sell our assets will have appropriate confidentiality and security measures, at least as protective as those described in this Privacy Policy, to handle your Personal Information. You will have the opportunity to opt out of any such transfer if the new entity's planned processing of your information differs materially from that set forth in this Privacy Policy.

4.4       A third party payment gateway provider may be required to collect certain financial information from you including, but not restricted to, your credit/debit card number or your bank account details (collectively referred to as “Financial Information”). All Financial Information collected from the you by such third party payment gateway providers will be used only for billing and payment processes. The Financial Information collected from you is transacted through secure digital platforms of approved payment gateways which are under encryption, thereby complying with reasonably expected technology standards. The verification of the Financial Information shall be accomplished only by you through a process of authentication in which we shall have no role to play and hence, we shall bear no liability in relation to the same. We shall neither be liable nor responsible for any actions or inactions of third party payment gateway providers or any breach of conditions, representations and warranties given by them. We shall also not be obligated to mediate or resolve any dispute or disagreement between you and such third party payment service providers.

4.5       While we take best efforts to ensure that your information including Personal Information, Financial Information and Sensitive Personal Information or Data is duly protected by undertaking security measures prescribed under applicable laws, you are strongly advised to exercise reasonable discretion while providing Personal Information or Financial Information while using the services given that the Internet is susceptible to security breaches.

4.6       Your information may also be transferred, stored or processed in any country other than the one where you access the Steve Madden Platform. For purposes of sharing or disclosing data in accordance with the Privacy Policy, we reserve the right to transfer your information outside of your country. By using the Steve Madden Platform, you consent to such transfer of your information outside of your country and also within our affiliates, subsidiaries and partners whose personnel and subcontractors, provided they have agreed to ensure the same level of data protection as prescribed under this Privacy Policy and the data protection laws of India. The information may be transferred in the event it is necessary for the performance of the services, operation of the Steve Madden Platform and provision of Products as agreed upon between us and the third party.
                                        </p>
                                    </div><div class="blog-content blog-details">
                                        <h5 class="blog-title">
                                            Security
                                        </h5>
                                       
                                        <p>5.1       The security of your Personal Information is important to us. We have implemented security policies, rules and technical measures, as required under applicable law including firewalls, transport layer security and other physical and electronic security measures to protect the Personal Information that it has under its control from unauthorized access, improper use or disclosure, unauthorized modification and unlawful destruction or accidental loss. When you submit your information on the Steve Madden Platform, your information is protected through our security systems. Please note that we use international and industry-recognized standards such as per applicable laws, rules and regulations.

5.2       Your information is contained within secured networks and is only accessible by a limited number of authorized persons who have access rights to such systems or otherwise require such information for the purposes provided in this Privacy Policy. These authorized persons are also under an obligation to keep such information confidential.

5.3       Although we make best possible efforts to transmit and store all the information provided by you in a secure operating environment that is not open to public, you understand and acknowledge that there is no such thing as complete security and we do not guarantee that there will be no unintended disclosures of any information and potential security breaches. You agree not to hold us responsible for any breach of security or for any action of any third parties that receive your Personal Information or events that are beyond our reasonable control including, acts of government, computer hacking, unauthorized access to computer data and storage device, computer crashes, breach of security and encryption, etc.
                                        </p>
                                    </div>
                                </div>
                              
                           
                            <!-- start blog comment box -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- blog main wrapper end -->
    </main> --}}

    <div class="mb-3 mb-xl-5 pt-1 pb-4"></div>
    <div class="mb-3 mb-xl-5 pt-1 pb-4"></div>
    <main>
        {{-- <div class="mb-4 pb-4"></div> --}}
        <section class="about-us container" style=" max-width: 100%; ">
          {{-- <div class="mw-930">
            <h2 class="page-title">ABOUT Walkcy</h2>
          </div> --}}
          <div class="about-us__content pb-5 mb-5">
            <div class="blog-main-wrapper section-padding">
                <div class="container">
                    <div class="row">
                       
                        <div class="col-lg-12 order-1">
                            <div class="row">
                                <div class="col-12">
                                    <!-- blog single item start -->
                                    <div class="blog-post-item">
                                        
                                        <h2><strong>Terms and Conditions</strong></h2>

<p>Welcome to Walkcy!</p>

<p>These terms and conditions outline the rules and regulations for the use of Walkcy's Website, located at https://walkcy.com/.</p>

<p>By accessing this website we assume you accept these terms and conditions. Do not continue to use Walkcy if you do not agree to take all of the terms and conditions stated on this page.</p>

<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: "Client", "You" and "Your" refers to you, the person log on this website and compliant to the Company's terms and conditions. "The Company", "Ourselves", "We", "Our" and "Us", refers to our Company. "Party", "Parties", or "Us", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client's needs in respect of provision of the Company's stated services, in accordance with and subject to, prevailing law of in. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>

<h3><strong>Cookies</strong></h3>

<p>We employ the use of cookies. By accessing Walkcy, you agreed to use cookies in agreement with the Walkcy's Privacy Policy. </p>

<p>Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p>

<h3><strong>License</strong></h3>

<p>Unless otherwise stated, Walkcy and/or its licensors own the intellectual property rights for all material on Walkcy. All intellectual property rights are reserved. You may access this from Walkcy for your own personal use subjected to restrictions set in these terms and conditions.</p>

<p>You must not:</p>
<ul>
    <li>Republish material from Walkcy</li>
    <li>Sell, rent or sub-license material from Walkcy</li>
    <li>Reproduce, duplicate or copy material from Walkcy</li>
    <li>Redistribute content from Walkcy</li>
</ul>

<p>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. Walkcy does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of Walkcy,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, Walkcy shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p>

<p>Walkcy reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</p>

<p>You warrant and represent that:</p>

<ul>
    <li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>
    <li>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</li>
    <li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</li>
    <li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>
</ul>

<p>You hereby grant Walkcy a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</p>

<h3><strong>Hyperlinking to our Content</strong></h3>

<p>The following organizations may link to our Website without prior written approval:</p>

<ul>
    <li>Government agencies;</li>
    <li>Search engines;</li>
    <li>News organizations;</li>
    <li>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and</li>
    <li>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</li>
</ul>

<p>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party's site.</p>

<p>We may consider and approve other link requests from the following types of organizations:</p>

<ul>
    <li>commonly-known consumer and/or business information sources;</li>
    <li>dot.com community sites;</li>
    <li>associations or other groups representing charities;</li>
    <li>online directory distributors;</li>
    <li>internet portals;</li>
    <li>accounting, law and consulting firms; and</li>
    <li>educational institutions and trade associations.</li>
</ul>

<p>We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of Walkcy; and (d) the link is in the context of general resource information.</p>

<p>These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party's site.</p>

<p>If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to Walkcy. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</p>

<p>Approved organizations may hyperlink to our Website as follows:</p>

<ul>
    <li>By use of our corporate name; or</li>
    <li>By use of the uniform resource locator being linked to; or</li>
    <li>By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party's site.</li>
</ul>

<p>No use of Walkcy's logo or other artwork will be allowed for linking absent a trademark license agreement.</p>

<h3><strong>iFrames</strong></h3>

<p>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</p>

<h3><strong>Content Liability</strong></h3>

<p>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</p>

<h3><strong>Reservation of Rights</strong></h3>

<p>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it's linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p>

<h3><strong>Removal of links from our website</strong></h3>

<p>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.</p>

<p>We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</p>

<h3><strong>Disclaimer</strong></h3>

<p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p>

<ul>
    <li>limit or exclude our or your liability for death or personal injury;</li>
    <li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
    <li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
    <li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>
</ul>

<p>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</p>

<p>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>


    
                                        
                                    </div>
                                  
                               
                                <!-- start blog comment box -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </section>
        
      
   
      </main>
    


@endsection
@section('extern-js')

<script src="{{url('plugins\datatables\jquery.dataTables.min.js')}}"></script>
<script src="{{url('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{url('plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{url('plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<script src="{{url('frontend_assets/custom_js/cart.js')}}"></script>
<script type="text/javascript"> $(document).ready(function(){
$(".small_img").hover (function(){
$(".big_img").attr('src', $(this).attr('src'));
});
});
</script>
<script type="text/javascript">
	$(document).ready(function(){
		$('#imgs').imagezoomsl({
			zoomrange:[3,3]
		});
	});
	function bigImg(obj){
		console.log(obj);
	}
</script>
@endsection